objects/Candidate__c.object
<CustomObject>
    <description>Candidate information</description>
    <fields>
        <fullName>Date_of_Birth__c</fullName>
        <description>Candidate&apos;s date of birth</description>
        <label>Date of Birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <label>Candidate</label>
    <nameField>
        <label>Candidate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Interview__c.object
<CustomObject>
    <fields>
        <fullName>Job_Id__c</fullName>
        <label>Job Title</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Interviews</relationshipLabel>
        <relationshipName>Candidate</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Interview</label>
    <nameField>
        <displayFormat>Interview-{0000}</displayFormat>
        <label>Interview Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Job__c.object
<CustomObject>
    <description>Job requirement from the concerned department /  line managers</description>
    <label>Job</label>
    <nameField>
        <label>Job Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/InterviewCC.cls
public with sharing class InterviewCC {

	public decimal pageSize {get;set;}

	public decimal totalPage {get;set;}

	public final Candidate__c candidate {get;set;}

	

	public InterviewCC() {
		
		Candidate__c[] candidates = [SELECT Name, Email__c, Phone__c, Date_of_Birth__c, Address__c,
										(SELECT Job_Id__c FROM Jobs__r) 
                     				  FROM Candidate__c where Id =: ApexPages.currentPage().getParameters().get('id')];
        if (candidates.size() > 0){
        	candidate = candidates[0];    
        	List<Interview__c> invList = new List<Interview__c>();

			/*for(Interview__c inv : candidate.Jobs__r)
			{
				invList.add(inv);	
			}     
			system.debug(invList);*/    				  
        }
	}


	public Candidate__c getCandidate() {
		return candidate;
	}

	/*public List<Interview__c> getInterviews() {
		List<Interview__c> invList = new List<Interview__c>();

		for(Interview__c inv : candidate.Jobs__r)
		{
			Interview__c[] juncObjects = [SELECT Name, (SELECT Name FROM Candidates__r)
										  FROM Job__c where ]	
		}
		system.debug(invList);
		return invList;
	}*/

	public Map<String, List<Interview__c>> getInterviews() {
		 Map<String,List<Interview__c>> mapC = new  Map<String,List<Interview__c>>();
    		
        	mapC.put(candidate.id, candidate.Jobs__r);
        	return mapC;
	}
}