objects/Candidate__c.object
<CustomObject>
    <description>Candidate information</description>
    <fields>
        <fullName>Date_of_Birth__c</fullName>
        <description>Candidate&apos;s date of birth</description>
        <label>Date of Birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Experience__c</fullName>
        <globalPicklist>Experience</globalPicklist>
        <label>Experience</label>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <globalPicklist>Gender</globalPicklist>
        <label>Gender</label>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <label>Source</label>
        <picklist>
            <picklistValues>
                <fullName>Advertisement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recruitment Web Portal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recruitment Consultant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employee Reference</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Word-of-mouth referral</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <label>Candidate</label>
    <nameField>
        <label>Candidate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Employee__c.object
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Interview__c.object
<CustomObject>
    <fields>
        <fullName>Candidate_Id__c</fullName>
        <label>Candidate Name</label>
        <referenceTo>Candidate__c</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Interviews</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Employee_Id__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Employee Name</label>
        <referenceTo>Employee__c</referenceTo>
        <relationshipLabel>Interviews</relationshipLabel>
        <relationshipName>Interviews</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Interview_Date__c</fullName>
        <label>Interview Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Job_Id__c</fullName>
        <label>Job Title</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Interviews</relationshipLabel>
        <relationshipName>Candidate</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Preliminary Test</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Final Interview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical Interview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Negotiation</fullName>
            </picklistValues>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <label>Interview</label>
    <nameField>
        <displayFormat>Interview-{0000}</displayFormat>
        <label>Interview Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Job__c.object
<CustomObject>
    <description>Job requirement from the concerned department /  line managers</description>
    <fields>
        <fullName>Employee_Id__c</fullName>
        <label>Employee_Id</label>
        <referenceTo>Employee__c</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Experience__c</fullName>
        <label>Experience</label>
        <picklist>
            <picklistValues>
                <fullName>New Graduate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>0 - 1 year</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1 - 3 years</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3 - 5 years</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5+ years</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Job_Category__c</fullName>
        <description>Job Category</description>
        <label>Job Category</label>
        <picklist>
            <picklistValues>
                <fullName>Accounting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Human Resource</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IT - Hardware / Network</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IT - Software</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Security</fullName>
            </picklistValues>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <picklist>
            <picklistValues>
                <fullName>Ho Chi Minh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Others</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <label>Job</label>
    <nameField>
        <label>Job Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/UpdatePassedStatusTriggerTest.cls
@isTest
public class UpdatePassedStatusTriggerTest {
    @isTest static void TestUpdatePassedStatus(){
        Candidate__c canc = new Candidate__c(Name='Test', Is_Passed__c = true,
                                             Email__c='a@b.c',Date_of_Birth__c = Date.newInstance(1992, 11, 01),
                                             Source__c='Advertisement',
                                             Gender__c='Male', Experience__c='0 - 1 year',
                                             Phone__c='1234567890'
                                            );
        insert canc;
        Employee__c emp = new Employee__c(Email__c='b.c@d.e');
        insert emp;
        Job__c j = new Job__c(Location__c = 'Others', Job_Category__c='Accounting',
                             Description__c = 'xyz');
        insert j;
        
        Interview__c inv = new Interview__c(Candidate_Id__c = canc.Id, Passed__c = false, Employee_Id__c = emp.Id,
                                           Interview_Date__c = Date.newInstance(2022, 11, 01),
                                            Type__c='Skype',
                                            Job_Id__c = j.Id
                                           );
        
        insert inv;
        
        Interview__c testchild = [Select Id, Passed__c
                                From Interview__c Where Id =: inv.Id];
        
		Candidate__c testParent = [Select Id, Is_Passed__c From Candidate__c where Id =: canc.Id];    
        System.assertEquals(testchild.Passed__c, testParent.Is_Passed__c);
    }
}