objects/Candidate__c.object
<CustomObject>
    <description>Candidate information</description>
    <fields>
        <fullName>Date_of_Birth__c</fullName>
        <description>Candidate&apos;s date of birth</description>
        <label>Date of Birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <globalPicklist>Gender</globalPicklist>
        <label>Gender</label>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <label>Candidate</label>
    <nameField>
        <label>Candidate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Passed_Candidate_Con.cls
public with sharing class Passed_Candidate_Con {

	public decimal pageNumber {get;set;}

	public decimal pageSize {get;set;}

	public decimal totalPage {get;set;}

	public integer resultSize {get;set;}


	public Passed_Candidate_Con() {
		pageSize = 5.0;
		pageNumber = 1;
		totalPage = 1;
		resultSize = 0;
	}

	public ApexPages.StandardSetController setCon {
        get {
            if(setCon == null) {
                setCon = new ApexPages.StandardSetController(Database.getQueryLocator(
                    [SELECT Name, Email__c, Phone__c, Date_of_Birth__c, Gender__c, Salary__c,
                     (SELECT Job_Id__c FROM Jobs__r) 
                     FROM Candidate__c WHERE Is_Passed__c = true]));
            }

            setCon.setPageSize((integer) pageSize);
            return setCon;
        }
        set;
    }

     public Boolean hasNext {
        get {
            return setCon.getHasNext();
        }
        set;
    }

    public Boolean hasPrevious {
        get {
            return setCon.getHasPrevious();
        }
        set;
    }

    public void previous()
    {
        setCon.previous();
    }


    public void next()
    {
        setCon.next();
    }

    // Initialize setCon and return a list of records
    public List<Candidate__c> getCandidates() {
    	List<Candidate__c> canList = setCon.getRecords();
    	resultSize = setCon.getResultSize();
    	system.debug('pagesize ' + pageSize);
    	pageNumber = setCon.getPageNumber();
    	if (resultSize == 0)
    	{
    		pageNumber = 0;
    		resultSize = 0;
    	}
    	totalPage = (resultSize / pageSize).round(System.RoundingMode.CEILING);

        return canList;
    }
}